"""Opt-in alignment of actual compiled SpiRob mesh-geom axes.

XML compilation centres meshes and chooses principal inertia axes. Rebase the
compiled representation *after* that step, before creating MjData or a renderer.
The returned model can be saved as MJB; saving/reloading XML loses this change.
This is deliberately limited to the pinned MuJoCo and standalone SpiRob meshes.
"""
from __future__ import annotations

import copy
import re

import mujoco
import numpy as np


def rotation(quat):
    result = np.empty(9)
    mujoco.mju_quat2Mat(result, quat)
    return result.reshape(3, 3)


def aligned_geom_model(model):
    """Return an independent model with link geom axes parallel to body axes.

    Geom centres remain at their compiled positions. Mesh vertices, normals,
    polygon normals and bounding boxes receive the compensating rotation;
    compiled body inertia, joints, sites and tendon/actuator data are retained.
    Geom-local sensor coordinates intentionally use the new axes.

    Reject shared meshes, noncanonical mesh placement, plugins, SDF/octrees,
    ellipsoid fluid forces and generated texture coordinates. Those cases need
    additional handling and are not generated by the standalone SpiRob build.
    Never mutate a model already in use by a viewer or simulation.
    """
    if mujoco.__version__ != '3.3.5':
        raise ValueError('Geom alignment is validated for MuJoCo 3.3.5; run uv sync --locked')
    if model.nplugin:
        raise ValueError('Geom alignment does not support plugin models')
    targets = []
    for gid in range(model.ngeom):
        body = model.body(model.geom_bodyid[gid]).name
        if not re.fullmatch(r'link_\d+', body):
            continue
        if model.geom_type[gid] != mujoco.mjtGeom.mjGEOM_MESH:
            continue
        mid = model.geom_dataid[gid]
        refs = np.flatnonzero((model.geom_dataid == mid) & np.isin(
            model.geom_type, [mujoco.mjtGeom.mjGEOM_MESH, mujoco.mjtGeom.mjGEOM_SDF]))
        if len(refs) != 1:
            raise ValueError(f'{body}: shared meshes are not supported for geom alignment')
        if model.mesh_octnum[mid] or np.any(model.geom_fluid[gid]):
            raise ValueError(f'{body}: octrees/fluid geoms are not supported for geom alignment')
        mat = model.geom_matid[gid]
        if mat >= 0 and np.any(model.mat_texid[mat] >= 0):
            raise ValueError(f'{body}: textured geoms are not supported for geom alignment')
        r = rotation(model.geom_quat[gid])
        authored = r @ rotation(model.mesh_quat[mid]).T
        if (not np.allclose(authored, np.eye(3), rtol=0, atol=1e-9)
                or not np.allclose(model.geom_pos[gid], model.mesh_pos[mid], rtol=0, atol=1e-9)):
            raise ValueError(f'{body}: authored mesh placement is not canonical; repair it before aligning frames')
        targets.append((gid, mid, r))
    if not targets:
        raise ValueError('No standalone link_NNN mesh geoms found for alignment')

    result = copy.copy(model)  # MuJoCo copies its model buffers, not just the Python wrapper.
    for gid, mid, r in targets:
        if np.array_equal(result.geom_quat[gid], [1, 0, 0, 0]):
            continue
        start = result.mesh_vertadr[mid]
        vertices = result.mesh_vert[start:start + result.mesh_vertnum[mid]]
        vertices[:] = vertices.astype(float) @ r.T
        start = result.mesh_normaladr[mid]
        normals = result.mesh_normal[start:start + result.mesh_normalnum[mid]]
        normals[:] = normals.astype(float) @ r.T
        start = result.mesh_polyadr[mid]
        normals = result.mesh_polynormal[start:start + result.mesh_polynum[mid]]
        normals[:] = normals @ r.T

        # Mesh BVH boxes live in the geom frame (body BVH boxes live in the
        # unchanged body inertial frame). Rotate boxes conservatively, including
        # a float-rounding allowance because mesh vertices are stored as float32.
        start = result.mesh_bvhadr[mid]
        boxes = result.bvh_aabb[start:start + result.mesh_bvhnum[mid]]
        padding = 4 * np.finfo(np.float32).eps * np.max(np.abs(vertices))
        boxes[:, :3] = boxes[:, :3] @ r.T
        boxes[:, 3:] = boxes[:, 3:] @ np.abs(r).T + padding
        lo, hi = vertices.astype(float).min(axis=0), vertices.astype(float).max(axis=0)
        result.geom_aabb[gid] = np.concatenate(((lo + hi) / 2, (hi - lo) / 2))
        result.geom_size[gid] = np.maximum(np.abs(lo), np.abs(hi))
        # Keep geom_rbound: rotation preserves its valid bounding sphere, and
        # this value also sets the convex collision solver's relative tolerance.

        inverse = result.geom_quat[gid].copy()
        inverse[1:] *= -1
        q = np.empty(4)
        mujoco.mju_mulQuat(q, result.mesh_quat[mid], inverse)
        result.mesh_quat[mid] = q
        result.geom_quat[gid] = [1, 0, 0, 0]
        # The compiler may have selected INERTIA; leaving that cached shortcut
        # in place would make mj_forward ignore the new geom quaternion.
        result.geom_sameframe[gid] = mujoco.mjtSameFrame.mjSAMEFRAME_BODYROT
    return result
